version: '3'

services:

  myapp-mysql:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=20002000
      - MYSQL_DATABASE=kambudb
      - MYSQL_USER=root
      - MYSQL_PASSWORD=20002000
    ports:
      - 3306:3306

  myapp-main:
    image: myapp-image-name-that-appears-when-you-run-docker-images
    restart: always
    depends_on:
      - myapp-mysql
    ports:
      - 8080:8080
    environment:
      - DATABASE_HOST=myapp-mysql
      - DATABASE_USER=root
      - DATABASE_PASSWORD=20002000
      - DATABASE_NAME=kambudb
      - DATABASE_PORT=3306